"use client";

import { useEffect, useMemo, useState } from "react";
import { FileCheck2, Pencil, Printer } from "lucide-react";
import {
  Badge,
  Button,
  Card,
  EmptyState,
  Label,
  PageHeader,
  Select,
  Skeleton,
} from "@pms/ui";
import type { SummaryResponse } from "@pms/types";
import { useAuthStore } from "@/lib/auth/auth-store";
import {
  useBranchSummaries,
  useFilterOptions,
  useSummary,
  useYoy,
} from "@/lib/analytics/use-analytics";

const INSTITUTION_NAME_KEY = "pms-report-institution-name";

const FUNNEL_ROWS: Array<{ label: string; field: keyof SummaryResponse }> = [
  { label: "Registered students", field: "totalStudents" },
  { label: "Eligible", field: "eligibleCount" },
  { label: "Applied", field: "appliedCount" },
  { label: "Shortlisted", field: "shortlistedCount" },
  { label: "Selected", field: "selectedCount" },
  { label: "Placed", field: "placedCount" },
];

function fmtCtc(v: number | null | undefined): string {
  return v == null ? "—" : `₹${v.toFixed(2)} LPA`;
}
function fmtPct(v: number | null | undefined): string {
  return v == null ? "—" : `${v.toFixed(1)}%`;
}

function SectionHeading({ index, title }: { index: number; title: string }) {
  return (
    <h2 className="mt-8 border-b-2 border-neutral-900 pb-1 text-sm font-bold uppercase tracking-wide text-neutral-900">
      {index}. {title}
    </h2>
  );
}

function ReportTable({
  head,
  rows,
}: {
  head: string[];
  rows: Array<Array<string | number>>;
}) {
  return (
    <table className="mt-3 w-full border-collapse text-[13px]">
      <thead>
        <tr>
          {head.map((h) => (
            <th
              key={h}
              className="border border-neutral-400 bg-neutral-100 px-3 py-1.5 text-left font-semibold text-neutral-900 [print-color-adjust:exact]"
            >
              {h}
            </th>
          ))}
        </tr>
      </thead>
      <tbody>
        {rows.map((row, i) => (
          <tr key={i}>
            {row.map((cell, j) => (
              <td key={j} className="border border-neutral-400 px-3 py-1.5 text-neutral-800">
                {cell}
              </td>
            ))}
          </tr>
        ))}
      </tbody>
    </table>
  );
}

export default function ReportStudioPage() {
  const role = useAuthStore((s) => s.user?.role);
  const [batchId, setBatchId] = useState<string | null>(null);
  const [institutionName, setInstitutionName] = useState("Your Institution");
  const [editingName, setEditingName] = useState(false);

  const isStaff = role === "SUPER_ADMIN" || role === "TPO" || role === "FACULTY_COORD";
  const filterOptions = useFilterOptions(isStaff);

  useEffect(() => {
    const saved = window.localStorage.getItem(INSTITUTION_NAME_KEY);
    if (saved) setInstitutionName(saved);
  }, []);

  useEffect(() => {
    if (!batchId && filterOptions.data?.batches.length) {
      setBatchId(filterOptions.data.batches[0]!.id);
    }
  }, [batchId, filterOptions.data, setBatchId]);

  const summary = useSummary({ batchId: batchId ?? undefined }, isStaff && !!batchId);
  const yoy = useYoy({ batchId: batchId ?? undefined }, isStaff && !!batchId);
  const departments = useMemo(
    () => filterOptions.data?.departments ?? [],
    [filterOptions.data],
  );
  const branchResults = useBranchSummaries(batchId, departments.map((d) => d.id));

  if (!isStaff) {
    return (
      <div className="mx-auto max-w-3xl">
        <Card>
          <EmptyState
            title="Report Studio is for placement staff"
            description="Accreditation reports are generated by TPOs, coordinators, and admins."
          />
        </Card>
      </div>
    );
  }

  const batch = filterOptions.data?.batches.find((b) => b.id === batchId);
  const data =
    summary.data && "totalStudents" in summary.data
      ? (summary.data as SummaryResponse)
      : undefined;
  const prev = yoy.data?.previous ?? null;

  const saveName = (name: string) => {
    const trimmed = name.trim() || "Your Institution";
    setInstitutionName(trimmed);
    window.localStorage.setItem(INSTITUTION_NAME_KEY, trimmed);
    setEditingName(false);
  };

  return (
    <div className="mx-auto max-w-4xl space-y-6">
      <div className="print:hidden">
        <PageHeader
          title="Report Studio"
          description="One click from live data to an accreditation-ready placement report — NIRF, NAAC, and AICTE formats expect exactly these tables."
          actions={
            <Button onClick={() => window.print()} disabled={!data}>
              <Printer className="h-4 w-4" />
              Print / Save as PDF
            </Button>
          }
        />
      </div>

      <Card className="print:hidden">
        <div className="flex flex-wrap items-end gap-4">
          <div>
            <Label htmlFor="report-batch">Academic batch</Label>
            <Select
              id="report-batch"
              className="mt-1 w-56"
              value={batchId ?? ""}
              onChange={(e) => setBatchId(e.target.value || null)}
            >
              <option value="" disabled>
                Select a batch
              </option>
              {filterOptions.data?.batches.map((b) => (
                <option key={b.id} value={b.id}>
                  {b.label}
                </option>
              ))}
            </Select>
          </div>
          <div className="flex-1" />
          <Badge tone="brand" dot>
            <FileCheck2 className="mr-1 h-3 w-3" />
            Live data — always current
          </Badge>
        </div>
      </Card>

      {summary.isLoading || filterOptions.isLoading ? (
        <Card>
          <div className="space-y-3">
            <Skeleton className="h-8 w-2/3" />
            <Skeleton className="h-40 w-full" />
            <Skeleton className="h-40 w-full" />
          </div>
        </Card>
      ) : !data ? (
        <Card>
          <EmptyState
            title="No placement summary for this batch yet"
            description="The report fills itself in as eligibility, applications, and offers start flowing."
          />
        </Card>
      ) : (
        <div className="rounded-[var(--radius-xl)] border border-neutral-200 bg-white p-8 shadow-[var(--shadow-md)] sm:p-12 print:rounded-none print:border-0 print:p-0 print:shadow-none">
          {/* ── Report header ── */}
          <div className="border-b-4 border-double border-neutral-900 pb-5 text-center">
            {editingName ? (
              <input
                autoFocus
                defaultValue={institutionName}
                onBlur={(e) => saveName(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === "Enter") saveName((e.target as HTMLInputElement).value);
                }}
                className="w-full max-w-md rounded border border-neutral-300 px-3 py-1 text-center text-2xl font-bold text-neutral-900 focus:outline-none"
                aria-label="Institution name"
              />
            ) : (
              <button
                type="button"
                onClick={() => setEditingName(true)}
                className="group inline-flex items-center gap-2 text-2xl font-bold tracking-tight text-neutral-900"
                title="Click to edit institution name"
              >
                {institutionName}
                <Pencil className="h-4 w-4 text-neutral-300 group-hover:text-neutral-500 print:hidden" />
              </button>
            )}
            <p className="mt-2 text-sm font-semibold uppercase tracking-widest text-neutral-700">
              Training &amp; Placement Cell
            </p>
            <p className="mt-1 text-base font-semibold text-neutral-900">
              Annual Placement Report — Batch {batch?.label ?? ""}
            </p>
            <p className="mt-1 text-xs text-neutral-500">
              Format aligned to NIRF / NAAC placement disclosures · Generated{" "}
              {new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" })}
            </p>
          </div>

          {/* ── 1. Executive summary ── */}
          <SectionHeading index={1} title="Executive summary" />
          <ReportTable
            head={["Indicator", "Value"]}
            rows={[
              ["Total registered students", data.totalStudents],
              ["Students placed", data.placedCount],
              ["Students unplaced", data.unplacedCount],
              ["Placement percentage", fmtPct(data.placementPercent)],
              ["Highest CTC", fmtCtc(data.highestCtc)],
              ["Median CTC", fmtCtc(data.medianCtc)],
              ["Average CTC", fmtCtc(data.averageCtc)],
              ["Participating recruiters", data.recruiterCount],
              ["Placement drives conducted", data.activeDriveCount],
            ]}
          />

          {/* ── 2. Placement funnel ── */}
          <SectionHeading index={2} title="Placement funnel & conversion" />
          <ReportTable
            head={["Stage", "Students", "% of registered"]}
            rows={FUNNEL_ROWS.map((row) => {
              const value = data[row.field] as number;
              const pct =
                data.totalStudents > 0
                  ? `${((value / data.totalStudents) * 100).toFixed(1)}%`
                  : "—";
              return [row.label, value, pct];
            })}
          />

          {/* ── 3. Branch-wise breakdown ── */}
          <SectionHeading index={3} title="Branch-wise placement" />
          {departments.length === 0 ? (
            <p className="mt-3 text-sm text-neutral-500">No departments configured.</p>
          ) : branchResults.some((r) => r.isLoading) ? (
            <Skeleton className="mt-3 h-32 w-full print:hidden" />
          ) : (
            <ReportTable
              head={["Branch", "Total", "Placed", "Placement %", "Median CTC", "Highest CTC"]}
              rows={departments.map((dept, i) => {
                const r = branchResults[i]?.data as SummaryResponse | undefined;
                if (!r || !("totalStudents" in r)) {
                  return [dept.name, "—", "—", "—", "—", "—"];
                }
                return [
                  dept.name,
                  r.totalStudents,
                  r.placedCount,
                  fmtPct(r.placementPercent),
                  fmtCtc(r.medianCtc),
                  fmtCtc(r.highestCtc),
                ];
              })}
            />
          )}

          {/* ── 4. Year-over-year ── */}
          <SectionHeading index={4} title="Year-over-year comparison" />
          {prev ? (
            <ReportTable
              head={["Indicator", `Batch ${batch?.label ?? "current"}`, "Previous batch", "Change"]}
              rows={[
                [
                  "Placement percentage",
                  fmtPct(data.placementPercent),
                  fmtPct(prev.placementPercent),
                  yoy.data?.placementPercentDelta != null
                    ? `${yoy.data.placementPercentDelta >= 0 ? "+" : ""}${yoy.data.placementPercentDelta.toFixed(1)} pts`
                    : "—",
                ],
                [
                  "Median CTC",
                  fmtCtc(data.medianCtc),
                  fmtCtc(prev.medianCtc),
                  yoy.data?.medianCtcDelta != null
                    ? `${yoy.data.medianCtcDelta >= 0 ? "+" : ""}₹${yoy.data.medianCtcDelta.toFixed(2)} LPA`
                    : "—",
                ],
                ["Students placed", data.placedCount, prev.placedCount, ""],
                ["Recruiters", data.recruiterCount, prev.recruiterCount, ""],
              ]}
            />
          ) : (
            <p className="mt-3 text-sm text-neutral-500">
              No previous batch data available for comparison.
            </p>
          )}

          {/* ── Signatures ── */}
          <div className="mt-16 grid grid-cols-3 gap-8 text-center text-xs text-neutral-700">
            {["Faculty Coordinator", "Training & Placement Officer", "Principal / Director"].map(
              (title) => (
                <div key={title}>
                  <div className="mx-auto w-full border-t border-neutral-500 pt-2">{title}</div>
                </div>
              ),
            )}
          </div>

          <p className="mt-10 border-t border-neutral-200 pt-3 text-center text-[10px] text-neutral-400">
            Generated from live placement records by PMS — data as of{" "}
            {new Date(data.computedAt).toLocaleString("en-IN")}. Every underlying record is
            audit-trailed.
          </p>
        </div>
      )}
    </div>
  );
}
